# https://taskfile.dev

version: '3'


tasks:
  venv:
    cmds:
      - python -m venv .venv
      - ".venv\\Scripts\\activate.bat"
      - pip install -r requirements.txt
    desc: разварачивает виртуальное окружение

  run-server-dev:
    cmds:
      - uvicorn --reload app:app
    desc: запускает сервер для разработки
    interactive: true

  run-tests:
    aliases: 
      - t
    cmds:
      - pytest .
    desc: запускает тесты

  code-format:
    aliases: 
      - f
    cmds:
      - black --exclude '.*venv.*' -l 79 .
    desc: форматирует код
