# https://taskfile.dev

version: '3'


tasks:
  venv:
    cmds:
      - python -m venv .venv
      - ".venv\\Scripts\\activate.bat"
      - pip install -r requirements.txt
    desc: разварачивает виртуальное окружение
